version: '3.8'

services:
  nextjs:
    image: node:18
    working_dir: /app
    volumes:
      - ./nextjs:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"

  node:
    image: node:18
    working_dir: /app
    volumes:
      - ./node:/app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: johnraptis
      POSTGRES_PASSWORD: password
      POSTGRES_DB: form_widget
    depends_on:
      - redis
    ports:
      - "4000:4000"
    command: sh -c "npm install && npm start"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: johnraptis
      POSTGRES_PASSWORD: password
      POSTGRES_DB: form_widget
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
